django_box/spotify/site_spotify/urls.py
from django.urls import path
from . import views

app_name = 'site_spotify'
urlpatterns = [
    path("", views.index, name="index"),
    path("c_home", views.c_home, name="c_home"),
    path("apiconnect", views.apiconnect, name="apiconnect"),
    path("urlredirect", views.urlredirect, name="urlredirect"),
    path("login", views.login, name="login"),
    path("register", views.register, name="register"),
    path("home", views.home, name="home"),
    path("chat", views.chat, name="chat"),
    path("forum", views.forum, name="forum"),
    path("findfriends", views.findfriends, name="findfriends"),
    path("stats", views.stats, name="stats"),
    path("connect", views.connect, name="connect"),
    path("logout", views.logout, name="logout"),
    path("testing", views.testing, name="testing"),
    path("thread/<int:id>", views.thread, name="thread"),
    path("room/<str:chat_recipient>", views.chatroom, name="chatroom"),
    path("sendchat", views.sendchat, name="sendchat"),
    path("getMessages/<str:room_id>", views.getMessages, name="getMessages"),
    path("details/<str:username>", views.recommended_details, name="details")
]

django_box/spotify/spotify/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('site_spotify/', include("site_spotify.urls"))
]

django_box/spotify/site_spotify/models.py
from django.db import models

# Create your models here.

django_box/spotify/site_spotify/forms.py
from django import forms

class RegisterForm(forms.Form):
    username = forms.CharField(label='User Name')
    pw = forms.CharField(widget=forms.PasswordInput, label="Password")
    pw2 = forms.CharField(widget=forms.PasswordInput,label="Retype Password")

class LoginForm(forms.Form):
    username = forms.CharField(label='User Name')
    pw = forms.CharField(widget=forms.PasswordInput,label="Password")

class PostThread(forms.Form):
    threadname = forms.CharField(label="Thread Name:")
    threadcontent = forms.CharField(widget=forms.Textarea, label="Discussion:")

class PostReply(forms.Form):
    replycontent = forms.CharField(widget=forms.Textarea, label="reply")

class AddFriend(forms.Form):
    addfriend = forms.CharField(label="", required=False)

class AddTrigger(forms.Form):
    add_trigger = forms.CharField(label="", required=False)

class RemoveTrigger(forms.Form):
    remove_trigger = forms.CharField(label="", required=False)

class SendChat(forms.Form):
    message = forms.CharField(label="", required=False)

class ProcessChatData(forms.Form):
    username = forms.CharField(label='')
    room_id = forms.CharField(label='')
    message = forms.CharField(label='')

django_box/spotify/site_spotify/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
#from site_spotify.db_auth_login import process_login
from site_spotify.register_user import register_user, process_login
from site_spotify.api_test import api_test
from site_spotify.forms import RegisterForm, LoginForm, PostThread, PostReply, AddFriend, SendChat, ProcessChatData
import uuid, json, traceback
from site_spotify.logPublisher import sendLog
from site_spotify.send_to_db import send_to_db
from site_spotify.process_threads import get_thread_info, get_reply_page, send_new_thread, send_new_reply
from site_spotify.process_threads import add_friend, get_friends, create_chat, get_username, new_chat_message, get_chat_messages, remove_friend
from site_spotify.process_threads import ThreadMain, ThreadReplies
from site_spotify.process_api import fetch_token, store_token_api, get_saved_tracks, get_stats_page, get_friend_recommendations, get_details_page
import datetime, random, json

saved_tracks = []

# Create your views here.
def index(request):
    if request.method == "POST":
        answer = process_login(request)
        print(answer)
        if answer != 'Not Found' and answer != 'error':
            return HttpResponseRedirect(reverse("site_spotify:dashboard"))
        else:
            answer = False
    else:
        answer = None
            
    return render(request, "site_spotify/index.html", {
        "login": answer
    })

def c_home(request):
    try:
        bad_login = False
        if request.method == 'POST':
            ## block for handling if form is registration
            form = RegisterForm(request.POST)
            if form.is_valid():
                print("register form valid")
                username = form.cleaned_data['username']
                pw = form.cleaned_data['pw']
                pw2 = form.cleaned_data['pw2']
                if not pw == pw2:
                    print("passwords don't match")
                    bad_login = True
                    return render(request, "site_spotify/register.html", {
                        "form": form, "bad_login": bad_login
                    })
                else:
                    registered = register_user(username, pw)
                    if registered:
                        print("user was registered")
                        print(registered)
                        sessionId = registered
                        response = render(request, "site_spotify/home.html")
                        response.set_cookie('sessionId', sessionId)
                        return response
                    else:
                        print("user was not registered, dup uname")
                        bad_login = True
                        return render(request, "site_spotify/register.html", {
                            "form": form, "bad_login": bad_login
                    })
            else:
                ## block for handling if form is regular login
                form = LoginForm(request.POST)
                print(request.POST)
                if form.is_valid():
                    print("loginForm form valid")
                    username = form.cleaned_data['username']
                    pw = form.cleaned_data['pw']
                    print(username, pw)

                    authentication = process_login(username, pw)
                
                    print(authentication)
                    if not authentication:
                        print("LOGIN FAIL1")
                        bad_login = True
                        return render(request, "site_spotify/login.html", {
                            "form": form, "bad_login": bad_login
                        })
                    #return HttpResponseRedirect(reverse("site_spotify:login"))
                else:
                    print("form not valid")
                    print("LOGIN FAIL2")
                    bad_login = True
                    return render(request, "site_spotify/login.html", {
                        "form": form, "bad_login": bad_login
                    })

            print("LOGIN SUCCESSFUL")
        
        sessionId = authentication

        response = render(request, "site_spotify/home.html")
        response.set_cookie('sessionId', sessionId)
        return response

    #
   # Mandatory Exception
   #
    except Exception as e:
        print(e)
        print(traceback.format_exc())
        sendLog("From Django views: " + str(e))

        return render(request, "site_spotify/login.html", {
        "form": LoginForm(), 
    })

def apiconnect(request):

    return render(request, "site_spotify/apiconnect.html")

def urlredirect(request):


    if request.method == 'GET':
        if 'code' in request.GET:
            code = request.GET['code']

    #request.session['access_token'] = token
    
    #return HttpResponseRedirect(reverse("site_spotify:dashboard"))

    return render(request, "site_spotify/fetchtoken.html", {
        "code": code
    })

def login(request):
    
    return render(request, "site_spotify/login.html", {
        "form": RegisterForm(), 
    })

def register(request):

    return render(request, "site_spotify/register.html", {
        "form": RegisterForm()

    })


# Main 5 website pages #
def home(request):
    try:
        #check for valid sessionID
        if 'sessionId' in request.COOKIES:
            print('cookie detected...')
            response = send_to_db(request.COOKIES['sessionId'], 'check_session')
            print(f"response: {response}")
            if not response:
                print('cookie is false or expired')
                session_expired = True
                response = render(request, "site_spotify/login.html", {
                    "form":LoginForm(), "session_expired": session_expired })
                response.delete_cookie('sessionId')
                print("session terminated")
                return response
        else:
            print("no cookie detected")
            please_log_in = True
            return render(request, "site_spotify/login.html", {
                "form": LoginForm(), "please_log_in": please_log_in})

        
        # take in spotifys code and get api token, then store db
        if request.method == 'GET':
            if 'code' in request.GET:
                code = request.GET['code']
                token = fetch_token(code)
                response = store_token_api(token, request.COOKIES['sessionId'])
        
        
        saved_tracks = get_saved_tracks(request.COOKIES['sessionId'])
        
        print("rendering...")
        return render(request, "site_spotify/home.html", {"saved_tracks": saved_tracks})

   #
   # Mandatory Exception
   #
    except Exception as e:
        print(e)
        print(traceback.format_exc())
        sendLog("From Django views: " + str(e))

        return render(request, "site_spotify/login.html", {
        "form": LoginForm(), 
    })
    

def chat(request):
    try:

        if 'sessionId' in request.COOKIES:
            print('cookie detected...')
            response = send_to_db(request.COOKIES['sessionId'], 'check_session')
            print(f"response: {response}")
            if not response:
                print('cookie is false or expired')
                session_expired = True
                response = render(request, "site_spotify/login.html", {
                    "form":LoginForm(), "session_expired": session_expired })
                response.delete_cookie('sessionId')
                print("session terminated")
                return response
        else:
            print("no cookie detected")
            return render(request, "site_spotify/login.html", {
                "form": LoginForm(), 
    })
        friend_response = True
        if request.method == 'POST':
            form = AddFriend(request.POST)
            print(request.POST)
            if form.is_valid():
                print("AddFriend form is valid")
                if 'add_trigger' in request.POST:
                    print("AddFriend valid on Add")
                    friendname = form.cleaned_data['addfriend']
                    print(friendname)
                    friend_response = add_friend(request.COOKIES['sessionId'], friendname)
                elif 'remove_trigger' in request.POST:
                    print("AddFriend valid on remove")
                    friendname = form.cleaned_data['addfriend']
                    friend_response = remove_friend(request.COOKIES['sessionId'], friendname)


        friends_list = get_friends(request.COOKIES['sessionId'])
        friend_number = len(friends_list)
            
        print("rendering...")
        return render(request, "site_spotify/chat.html", {
            "form": AddFriend(), "friends_list": friends_list, "friend_number": friend_number,
            "friend_response": friend_response
        })

   #
   # Mandatory Exception
   #
    except Exception as e:
        print(e)
        print(traceback.format_exc())
        sendLog("From Django views: " + str(e))

        return render(request, "site_spotify/login.html", {
        "form": LoginForm(), 
    })

def chatroom(request, chat_recipient):

    try:

        if 'sessionId' in request.COOKIES:
            print('cookie detected...')
            response = send_to_db(request.COOKIES['sessionId'], 'check_session')
            print(f"response: {response}")
            if not response:
                print('cookie is false or expired')
                session_expired = True
                response = render(request, "site_spotify/login.html", {
                    "form":LoginForm(), "session_expired": session_expired })
                response.delete_cookie('sessionId')
                print("session terminated")
                return response
        else:
            print("no cookie detected")

django_box/spotify/site_spotify/templates/site_spotify/another_test.html
{% extends "site_spotify/main_template.html" %}
{% load static %}

{% block body %}
<script src="{% static 'site_spotify/jquery.min.js' %}"></script>
<style>

#colorlib-main{
        
        align-items: center;
        justify-content: center;
        min-height: 100vh;
        margin: 0;
}

#btn {
        background-color: #47a386;
        border: 0;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.2);
        color: #fff;
        font-size: 14px;
        padding: 10px 25px;
}



.after_modal_appended
{  
  position:relative;
}

.red
{
  background-color:red;
}

.blue
{
  background-color:blue;
  
}

.block 
{
  width:100%;
  height:600px;
}

.modal, .modal-backdrop {
    position: absolute !important;
}



</style>

<div>
    <button id="btn">Add Thread</button>
    <!--<div class="red block">
    </div>-->
    
    <div >
         <!-- Modal -->
      <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
  
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <!--<button type="button" class="close" data-dismiss="modal">&times;</button>-->
              <h4 class="modal-title">Add Thread</h4>
            </div>
            <div class="modal-body">
                <form action="">
                    <input type="text" placeholder="Thread Name">
                    <input type="text" placeholder="Discussion">
                    <button href="#" id="close">Submit</button>
                </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
  
        </div>
      </div>
      <ul>
        
            <li>test1</li>
            <li>test2</li>
            <li>No saved tracks.</li>
            <li>testing3</li>
            <li>testing4</li>
      

    </ul>


   </div>
    
  </div>
  <script>
    $(document).ready(function(){
	
        $("body").on("click","#btn",function(){
           
            $("#myModal").modal("show");
       
            $(".blue").addClass("after_modal_appended");
   
            //appending modal background inside the blue div
            $('.modal-backdrop').appendTo('.blue');   
   
            //remove the padding right and modal-open class from the body tag which bootstrap adds when a modal is shown
   
            $('body').removeClass("modal-open")
                $('body').css("padding-right","");     
 });

});
  </script>
  
  
  {% endblock %}

django_box/spotify/site_spotify/templates/site_spotify/apiconnect.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <title>Dashboard</title>
    </head>
        <body>
           
            
            <script>
              /*
              const APIController = (function() {

                const clientId = '';
                const clientSecret = '';

                const _getToken = async () => {
                
                  const result = await fetch('https://accounts/spotify.com/api/token', {
                    method: 'POST', 
                    headers: {
                      'Content-Type' : 'application/x-www-form-urlencoded',
                      'Authorization' : 'Basic' + btoa(cliendId + ':' + clientSecret)
                    },
                    body: 'grant_type=implicit_grant'
                });

                const data = await result.json();
                return data.access_token;
                }

              })();
                */
              

              var client_id = '4ed36c33643a4974817619f60d7615cd';
              //var redirect_uri = 'http://10.202.4.226/site_spotify/home';
              var redirect_uri = 'http://192.168.1.4/site_spotify/home';
              var authorize = 'https://accounts.spotify.com/authorize';
              var scope = 'user-library-read user-top-read user-follow-read';


              function requestAuthorization(){
                localStorage.setItem("client_id", client_id);

                let url = authorize;
                url += "?client_id=" + client_id;
                url += "&response_type=code";
                url += "&redirect_uri=" + encodeURI(redirect_uri);
                url += "&show_dialog=true";
                url += "&scope=user-library-read user-top-read user-follow-read";
                window.location.href = url; // Show Spotify's authorization screen

              }

              
              requestAuthorization();

            </script>
           
        </body>
</html>

django_box/spotify/site_spotify/templates/site_spotify/fetchtoken.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> 
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <title>Fetching token..</title>
    </head>
        <body>
           {{ code|json_script:"code" }}
           {% csrf_token %}

            <script>
                const TOKEN = "https://accounts.spotify.com/api/token";
                var client_id = '';
                var client_secret = '';
                var redirect_uri = 'http://192.168.1.3/site_spotify/urlredirect';
                var authorize = 'https://accounts.spotify.com/api/token';
                var scope = 'user-library-read';
                var toke;
                
                function fetchAccessToken( code ){
                    let body = "grant_type=authorization_code";
                    body += "&code=" + code; 
                    body += "&redirect_uri=" + encodeURI(redirect_uri);
                    body += "&client_id=" + client_id;
                    body += "&client_secret=" + client_secret;
                    callAuthorizationApi(body);

                }
                function callAuthorizationApi(body){
                    let xhr = new XMLHttpRequest();
                    xhr.open("POST", TOKEN, true);
                    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
                    xhr.setRequestHeader('Authorization', 'Basic ' + btoa(client_id + ":" + client_secret));
                    xhr.send(body);
                    xhr.onload = handleAuthorizationResponse;

                }
                
                function handleAuthorizationResponse(){
                    if ( this.status == 200 ){
                        var data = JSON.parse(this.responseText);
                        console.log(data);
                        var data = JSON.parse(this.responseText);
                        if ( data.access_token != undefined ){
                            access_token = data.access_token;
                            sessionStorage.setItem("access_token", access_token);
                            
                            console.log("Token is: "+access_token)
                        }
                        if ( data.refresh_token  != undefined ){
                            refresh_token = data.refresh_token;
                            sessionStorage.setItem("refresh_token", refresh_token);
                        }
                        //onPageLoad();
                        console.log('sending token to dashboard')
                        sendTokenData(access_token)
                    }
                    else {
                        console.log(this.responseText);
                        alert(this.responseText);
                    
                    
                    }
                }

                function sendTokenData(token_data){
                    
                    $.ajax({
                        type: "POST",
                        url: '/site_spotify/dashboard',
                        data: {
                            "csrfmiddlewaretoken": $("input[name=csrfmiddlewaretoken]").val(),
                            "token": token_data,
                        },
                        dataType: "json",
                        


                    });
                    //window.location.href = '/site_spotify/dashboard'
                    
                    

                    
                    
                    /*
                    url = "{% url 'site_spotify:home' %}";
                    data = {
                        "csrfmiddlewaretoken": $("input[name=csrfmiddlewaretoken]").val(),
                        "token": token_data}
                    $.post(url, token_data, function(response){
                        if(resposne === 'success'){console.log("It worked");}
                        else{console.log("it failed");}
                    });
                    */

                }
                
                const code = JSON.parse(document.getElementById("code").textContent);
                
                fetchAccessToken( code );

                //var token = sessionStorage.access_token;
                //alert(token)

                //sendTokenData(token);


            </script>
            <h3 class="h3 mb-3 fw-normal center"><a href='home'>Success! Click here to view Dashboard!</a></h3>

        </body>
</html>

django_box/spotify/site_spotify/templates/site_spotify/forum.html
{% extends "site_spotify/main_template.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block body %}
<script src="{% static 'site_spotify/jquery.min.js' %}"></script>
<style>

#colorlib-main{
        
        align-items: center;
        justify-content: center;
        min-height: 100vh;
        margin: 0;
}

#btn {
        background-color: #47a386;
        border: 0;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.2);
        color: #fff;
        font-size: 14px;
        padding: 10px 25px;
        margin-bottom: 10px;
        margin-left: 18px;
}
.tango {
        background-color: #47a386;
        border: 0;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0,0,0,0.2);
        color: #fff;
        font-size: 14px;
        padding: 10px 25px;
}


.after_modal_appended
{  
  position:relative;
}

.red
{
  background-color:red;
}

.blue
{
  background-color:blue;
  
}

.block 
{
  width:100%;
  height:600px;
}

.modal, .modal-backdrop {
    position: absolute !important;
}



</style>

<div>
    <button id="btn">Add Thread</button>
    <!--<div class="red block">
    </div>-->
    
    <div >
         <!-- Modal -->
      <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
  
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <!--<button type="button" class="close" data-dismiss="modal">&times;</button>-->
              <h4 class="modal-title">Add Thread</h4>
            </div>
            <div class="modal-body">
                <form action="{% url 'site_spotify:forum' %}" method="post">
                    {% csrf_token %}
                    {{ form.errors }}
                    <!--<input type="text" placeholder="Thread Name">-->
                    {{ form.threadname|as_crispy_field }}
                    <!--<input type="text" placeholder="Discussion">-->
                    {{ form.threadcontent|as_crispy_field }}
                    <input class="tango" id="close" type='submit' value="submit">
                </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>
  
        </div>
      </div>

      {% for thread in thread_posts %} 
      <div class="container">
        <div class="card mb-3">
            <div class="card-body">
                <h4 class="card-title"><a href="/site_spotify/thread/{{ thread.threadID }}">{{ thread.title }}</a></h4>
                <p class="card-text">
                  {{ thread.content }}
                </p>
                <p>
                    <a class="mr-2">{{ thread.author }}</a>
                    <a class="mr-2">5 Replies</a>
                    <a class="mr-2"> {{ thread.date }}</a>
                </p>
            </div>
        </div>
    </div>
    {% empty %}
    <ul>
      <li> No thread posts.</li>
    </ul>
    {% endfor %}

   </div>
    
  </div>
  <script>
    $(document).ready(function(){
	
        $("body").on("click","#btn",function(){
           
            $("#myModal").modal("show");
       
            $(".blue").addClass("after_modal_appended");
   
            //appending modal background inside the blue div
            $('.modal-backdrop').appendTo('.blue');   
   
            //remove the padding right and modal-open class from the body tag which bootstrap adds when a modal is shown
   
            $('body').removeClass("modal-open")
                $('body').css("padding-right","");     
 });

});
  </script>
  
  
  {% endblock %}

django_box/spotify/site_spotify/templates/site_spotify/main_template.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
<title>Dashboard</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,300,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'site_spotify/sidebar.css' %}">
</head>
<body>
<div id="colorlib-page">
<a href="#" class="js-colorlib-nav-toggle colorlib-nav-toggle"><i></i></a>
<aside id="colorlib-aside" role="complementary" class="js-fullheight">
<nav id="colorlib-main-menu" role="navigation">
<ul>
<li class="colorlib-active"><a href="{% url 'site_spotify:home' %}">Home</a></li>
<li><a href="{% url 'site_spotify:findfriends' %}">Find Friends</a></li>
<li><a href="{% url 'site_spotify:forum' %}">Forum</a></li>
<li><a href="{% url 'site_spotify:chat' %}">Chat</a></li>
<li><a href="{% url 'site_spotify:stats' %}">Stats</a></li>
<li><a href="{% url 'site_spotify:connect' %}">Connect</a></li>
<li><a href="{% url 'site_spotify:logout' %}">Logout</a></li>
</ul>
</nav>
</aside> 
<div id="colorlib-main">
{% block body %}
{% endblock %}
</div>
</div>
</section>
<script src="{% static 'site_spotify/jquery.min.js' %}"></script>
<script src="{% static 'site_spotify/popper.js+bootstrap.min.js+main.js.pagespeed.jc.Lw9Dax5Poq.js' %}"></script><script>eval(mod_pagespeed_CzR6znllV0);</script>
<script>eval(mod_pagespeed_K3B2X0HP2y);</script>
<script>eval(mod_pagespeed_C5gykd7_I_);</script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"6a5a365d5241efc4","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.10.0","si":100}'></script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"6a5a365d2a76efc4","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.10.0","si":100}'></script>


</body>
</html>

django_box/spotify/site_spotify/templates/site_spotify/thread.html
{% extends "site_spotify/main_template.html" %}
{% load crispy_forms_tags %}
{% block body %}
<style>
.tango {
    background-color: #47a386;
    border: 0;
    border-radius: 5px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.2);
    color: #fff;
    font-size: 14px;
    padding: 10px 25px;
}
</style>

    <div class="container">
        <h2>{{ thread.title }}</h2>
        <p>
            <span class="mr-4">{{ thread.date }}</span>
            <!--<a> {{ thread.author }}</a>-->
        </p>
    </div>
    <hr/>
    <div class="row">
        <div class="col-1"></div>

        <div class="col-11">
            <p>
                {{ thread.content }}
            </p>
            <p>
                <a href="#" class="mr-3">{{ thread.author }}</a>
                <span>{{ reply_count }} replies</span>
            </p>
            <!-- Replies section-->
            <h3 class="my-2">Replies</h3>
            {% for reply in reply_list %}
            <div class="card mb-2">
                <div class="card-body">
                    <p>{{ reply.content }}</p>
                    <p>
                        <a href="#" class="mr-2">{{ reply.author }}</a>
                        <a>{{ reply.date }}</a>
                    </p>
                </div>
            </div>
            {% endfor %}
                    <!-- Reply Form -->
            <div class="card">
                <h6 class="card-header">Post Reply</h6>
                <div class="card-body">
                    <form action="/site_spotify/thread/{{ thread.threadID }}" method="post">
                        {% csrf_token %}
                        {{ form.errors }}
                        {{ form.replycontent|as_crispy_field }}

                        <input class="tango" id="close" type='submit' value="submit">
                    <!--<textarea class="form-control comment-text"></textarea>
                    <button type=button class="btn btn-dark my-3 save-comment">Submit</button>-->
                </div>
            </div>
            <a href="{% url 'site_spotify:forum' %}">Go Back</a>
        </div>

    </div>
    


{% endblock %}

django_box/spotify/site_spotify/templates/site_spotify/threadlist.html
{% extends "site_spotify/threadlist.html" %}

{% block body %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Question</h4>
            <p class="card-text">Question details</p>
            <p>
                <a href="#" class="mr-3">john</a>
                <a href="#" class="mr-3">john</a>
                <a href="#" class="mr-3">john</a>
            </p>
        </div>
    </div>
</div>

{% endblock %}